version: '3.8'
services:
  db_service_child:
    container_name: auth_service
    build:
      context: .
      dockerfile: db_service.dockerfile
    ports:
      - 8888:8888
    volumes:
      - .:/opt/code
    networks:
      - cmsc495_network
    depends_on:
      - db
    env_file:
      - ../db-service/data_db.env


networks:
  cmsc495_network:
    external: true
    name: cmsc495_network