version: '3.8'
services:
  auth_service:
    container_name: auth_service
    build:
      context: .
      dockerfile: auth_service.dockerfile
    ports:
      - 8888:8888
    volumes:
      - .:/opt/code
    networks:
      - cmsc495_network
    depends_on:
      - auth_db
    env_file:
      - ../db-service/auth_db.env


networks:
  cmsc495_network:
    external: true
    name: cmsc495_network
