version: '3.8'
services:
  db_service:
    container_name: db_service
    build:
      context: .
      dockerfile: db_service.dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/opt/code
    networks:
      - cmsc495_network
    depends_on:
      - db


networks:
  cmsc495_network:
    external: true
    name: cmsc495_network
